# Generated by Django 6.1.2 on 2026-10-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_trade_signal'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='portfolio.portfolio'),
        ),
        migrations.AddConstraint(
            model_name='tradingsignal',
            constraint=models.UniqueConstraint(fields=('portfolio', 'stock', 'signal_date', 'signal_type'), name='unique_portfolio_stock_signal'),
        ),
    ]
