# Generated by Django 6.1.2 on 2026-10-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'permissions': [('execute_paper_trade', 'Can submit and refresh paper trades')]},
        ),
    ]
