# Generated by Django 6.1.2 on 2026-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_trade_signal'),
        ('trading', '0002_tradingsignal_portfolio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('signal',), name='unique_order_per_signal'),
        ),
    ]
